const CURRENT_VIEW = 'CURRENT_VIEW';
const REVIEW = 'REVIEW';
const COMPLETED_VIEW = 'COMPLETED_VIEW';
const FAVORITE_VIEW = 'FAVORITE_VIEW';



module.exports = {
    CURRENT_VIEW,
    REVIEW,
    FAVORITE_VIEW,
    COMPLETED_VIEW
}